name: release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: java env
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "17"

      - name: flutter env
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.1"

      - run: flutter pub get
      # - run: flutter test
      - name: Collect Apks
        run: flutter build apk --release --split-per-abi -v

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: ${{steps.github_release.outputs.changelog}}
          files: |
            build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
            build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
            build/app/outputs/flutter-apk/app-x86_64-release.apk
