name: release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: java env
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "17"

      - name: flutter env
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.1"

      - run: flutter pub get
      # - run: flutter test
      - name: Collect Apks
        run: flutter build apk --release --split-per-abi -v

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Artifact - armeabi-v7a
        uses: actions/upload-artifact@v4
        with:
          path: "build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk"
          name: local_novel_reader-armeabi-v7a.apk
      - name: Upload Artifact - arm64-v8a
        uses: actions/upload-artifact@v4
        with:
          path: "build/app/outputs/flutter-apk/app-arm64-v8a-release.apk"
          name: local_novel_reader-arm64-v8a.apk
      - name: Upload Artifact - x86
        uses: actions/upload-artifact@v4
        with:
          path: "build/app/outputs/flutter-apk/app-x86_64-release.apk"
          name: local_novel_reader-x86_64.apk
